### ISSUE TITLE
working on it 

### ISSUE THREAD

**Issue by vermad843** [CodingGarden/meower#4]
hey cj huge fan. love the way you teach. thankyou for your valuable content. I am working on this please accept my request.

**Comment by vermad843** [comment]
C:\Users\vishnu\Desktop\workspace\meower>git push origin adding-styles
remote: Permission to CodingGarden/meower.git denied to vermad843.
fatal: unable to access 'https://github.com/CodingGarden/meower.git/': The requested URL returned error: 403

**Comment by w3cj** [comment]
1. Fork the repo
2. Add your fork as a remote locally

```
git remote add my-remote https://github.com/vermad843/meower.git
```

3. Push the changes to your remote

```
git push my-remote master
```

4. Open a pull request with the changes you made

**Comment by vermad843** [comment]
thank you, CJ for taking time out for answering this
 I followed this and it worked and
 I opened the pull request as well please check .thankyou!!!!
